//! The `LIMIT` clause of a select statement.
//!
//! Written out rather than generated by `simple_clause!` like its `OFFSET`
//! neighbour, because a `LIMIT` value is the one part of a select where a
//! backend may not be free to use a bind parameter: a database can accept
//! `LIMIT ?` at the top level of a statement and quietly refuse it inside a
//! subquery. [`SqlDialect::SubselectLimitSyntax`] is where a backend says so,
//! and everything else here matches what the macro would have written.

use super::{AstPass, QueryFragment};
use crate::backend::{sql_dialect, Backend, DieselReserveSpecialization, SqlDialect};
use crate::query_builder::QueryId;
use crate::result::QueryResult;

/// A query node indicating the absence of a limit clause
///
/// This type is only relevant for implementing custom backends
#[cfg_attr(
    feature = "i-implement-a-third-party-backend-and-opt-into-breaking-changes",
    cfg(feature = "i-implement-a-third-party-backend-and-opt-into-breaking-changes")
)]
#[derive(Debug, Clone, Copy, QueryId)]
pub struct NoLimitClause;

impl<DB> QueryFragment<DB> for NoLimitClause
where
    DB: Backend + DieselReserveSpecialization,
{
    fn walk_ast<'b>(&'b self, _: AstPass<'_, 'b, DB>) -> QueryResult<()> {
        Ok(())
    }
}

/// A query node representing a limit clause
///
/// This type is only relevant for implementing custom backends
#[cfg_attr(
    feature = "i-implement-a-third-party-backend-and-opt-into-breaking-changes",
    cfg(feature = "i-implement-a-third-party-backend-and-opt-into-breaking-changes")
)]
#[derive(Debug, Clone, Copy, QueryId)]
pub struct LimitClause<Expr>(pub Expr);

impl<Expr, DB> QueryFragment<DB> for LimitClause<Expr>
where
    DB: Backend,
    Self: QueryFragment<DB, DB::SubselectLimitSyntax>,
{
    fn walk_ast<'b>(&'b self, pass: AstPass<'_, 'b, DB>) -> QueryResult<()> {
        <Self as QueryFragment<DB, DB::SubselectLimitSyntax>>::walk_ast(self, pass)
    }
}

impl<Expr, DB> QueryFragment<DB, sql_dialect::subselect_limit_syntax::BindSubselectLimit>
    for LimitClause<Expr>
where
    DB: Backend
        + DieselReserveSpecialization
        + SqlDialect<SubselectLimitSyntax = sql_dialect::subselect_limit_syntax::BindSubselectLimit>,
    Expr: QueryFragment<DB>,
{
    fn walk_ast<'b>(&'b self, mut out: AstPass<'_, 'b, DB>) -> QueryResult<()> {
        out.push_sql(" LIMIT ");
        self.0.walk_ast(out.reborrow())?;
        Ok(())
    }
}
