//! `TaggedUnion<E>` — diesel SqlType marker for turso UNION columns, plus
//! the encode/decode helpers that user-side `ToSql` / `FromSql` impls call
//! through to.
//!
//! Named `TaggedUnion` rather than `Union` because SQL already has a
//! `UNION`, and diesel already models it:
//! `query_builder::combination_clause::Union` and `CombineDsl::union` are
//! the set operation that stacks two result sets. A `sql_types::Union`
//! sitting beside those would read, in a `table!` block, as if the column
//! were something to do with that. `TaggedUnion` says what the type
//! actually is — a tag byte selecting one of several payload shapes.
//!
//! Orphan rules prevent a generic `impl<E: UnionSchema>
//! ToSql<TaggedUnion<E>, Turso> for E`. Instead, each user enum gets a
//! per-type impl (generated by `#[derive(UnionSchema)]` — or hand-written,
//! see `tests/m7_union_codec.rs`) whose body is a one-liner forwarding to
//! [`encode_for_bind`] / [`decode_from_blob`].

use std::marker::PhantomData;

use crate::deserialize;
use crate::serialize::{self, IsNull, Output};
use crate::sql_types::{HasSqlType, SqlType};

use super::wire::{decode_union, encode_union};
use super::{DecodeError, UnionSchema, ValueKind};
use crate::turso::backend::{Turso, TursoType};
use crate::turso::value::TursoValue;

/// Diesel `SqlType` marker for a turso UNION column whose Rust-side
/// representation is `E`. Users write `data -> TaggedUnion<MyEnum>` in
/// their `table!` macro.
#[derive(SqlType, crate::query_builder::QueryId, Debug, Clone, Copy, Default)]
pub struct TaggedUnion<E: 'static>(PhantomData<fn() -> E>);

impl<E: 'static> TaggedUnion<E> {
    /// The marker value. Carries no data — `E` is the whole type.
    pub const fn new() -> Self {
        Self(PhantomData)
    }
}

impl<E: 'static> HasSqlType<TaggedUnion<E>> for Turso {
    fn metadata(_: &mut ()) -> TursoType {
        TursoType::Binary
    }
}

/// Encode a UnionSchema instance to its wire-format blob and park it in
/// diesel's `Output` as a single bind value. One-liner for user-side
/// `ToSql<TaggedUnion<E>, Turso> for E` impls.
pub fn encode_for_bind<E>(value: &E, out: &mut Output<'_, '_, Turso>) -> serialize::Result
where
    E: UnionSchema,
{
    out.set_value(encode_union(value.tag_index(), value.encode_outer()?));
    Ok(IsNull::No)
}

/// Decode a wire blob into `E` via the user's `UnionSchema::decode`.
/// One-liner for user-side `FromSql<TaggedUnion<E>, Turso> for E` impls.
pub fn decode_from_blob<E>(bytes: TursoValue<'_>) -> deserialize::Result<E>
where
    E: UnionSchema,
{
    let value = bytes.as_turso();
    let blob = match value {
        turso::Value::Blob(b) => b.as_slice(),
        other => {
            return Err(Box::new(DecodeError::TypeMismatch {
                expected: "UNION blob",
                got_kind: ValueKind::of(other),
            }) as _);
        }
    };
    let (index, outer) = decode_union(blob).map_err(DecodeError::from)?;
    E::decode(index, outer).map_err(|e| Box::new(e) as _)
}
