//! M7 acceptance: a hand-written `UnionSchema` impl roundtrips end-to-end
//! through the diesel DSL against `TursoConnection`. This is what the
//! M8 `#[derive(UnionSchema)]` macro will produce mechanically.

use anyhow::Result;
use diesel::async_dsl::RunQueryDsl;
use diesel::connection::{AsyncConnection, SimpleAsyncConnection};
use diesel::deserialize::{FromSql, FromSqlRow};
use diesel::expression::AsExpression;
use diesel::prelude::*;
use diesel::serialize::{Output, ToSql};
use diesel::turso::union::{
    decode_from_blob, decode_record, encode_for_bind, encode_record, DecodeError, TaggedUnion,
    UnionSchema,
};
use diesel::turso::Turso;
use diesel::turso::TursoConnection;

// Hand-written UnionSchema impl below — M8 generates the equivalent block
// from `#[derive(UnionSchema)]`. Kept here as a regression target for the
// codec, in case the derive ever changes shape.
#[derive(Debug, PartialEq, Clone, FromSqlRow, AsExpression, diesel::query_builder::QueryId)]
#[diesel(sql_type = TaggedUnion<MessageData>)]
pub enum MessageData {
    Telegram {
        chat_id: i64,
        text: String,
    },
    Slack {
        channel_id_hash: i64,
        text: Option<String>,
    },
}

impl UnionSchema for MessageData {
    fn type_name() -> &'static str {
        "message_data"
    }

    fn variants() -> &'static [&'static str] {
        &["telegram", "slack"]
    }

    fn variant_fields() -> &'static [&'static [&'static str]] {
        &[&["chat_id", "text"], &["channel_id_hash", "text"]]
    }

    fn tag_index(&self) -> u8 {
        match self {
            Self::Telegram { .. } => 0,
            Self::Slack { .. } => 1,
        }
    }

    fn encode_outer(&self) -> diesel::turso::union::EncodeResult<turso::Value> {
        let fields: Vec<turso::Value> = match self {
            Self::Telegram { chat_id, text } => vec![
                turso::Value::Integer(*chat_id),
                turso::Value::Text(text.clone()),
            ],
            Self::Slack {
                channel_id_hash,
                text,
            } => vec![
                turso::Value::Integer(*channel_id_hash),
                match text {
                    Some(s) => turso::Value::Text(s.clone()),
                    None => turso::Value::Null,
                },
            ],
        };
        Ok(turso::Value::Blob(encode_record(&fields)))
    }

    fn decode(index: u8, outer: turso::Value) -> Result<Self, DecodeError> {
        let inner_blob = match outer {
            turso::Value::Blob(b) => b,
            other => {
                return Err(DecodeError::Custom(format!(
                    "expected struct blob: {other:?}"
                )));
            }
        };
        let fields = decode_record(&inner_blob)?;
        match index {
            0 => {
                let mut it = fields.into_iter();
                let chat_id = match it.next() {
                    Some(turso::Value::Integer(i)) => i,
                    other => {
                        return Err(DecodeError::Custom(format!("telegram.chat_id: {other:?}")));
                    }
                };
                let text = match it.next() {
                    Some(turso::Value::Text(s)) => s,
                    other => return Err(DecodeError::Custom(format!("telegram.text: {other:?}"))),
                };
                Ok(Self::Telegram { chat_id, text })
            }
            1 => {
                let mut it = fields.into_iter();
                let channel_id_hash = match it.next() {
                    Some(turso::Value::Integer(i)) => i,
                    other => {
                        return Err(DecodeError::Custom(format!(
                            "slack.channel_id_hash: {other:?}"
                        )));
                    }
                };
                let text = match it.next() {
                    Some(turso::Value::Null) => None,
                    Some(turso::Value::Text(s)) => Some(s),
                    other => return Err(DecodeError::Custom(format!("slack.text: {other:?}"))),
                };
                Ok(Self::Slack {
                    channel_id_hash,
                    text,
                })
            }
            other => Err(DecodeError::UnknownVariant {
                index: other,
                expected: Self::variants(),
            }),
        }
    }

    fn create_type_sql() -> String {
        "CREATE TYPE telegram_t AS STRUCT(chat_id INT, text TEXT); \
         CREATE TYPE slack_t AS STRUCT(channel_id_hash INT, text TEXT); \
         CREATE TYPE message_data AS UNION(telegram telegram_t, slack slack_t)"
            .into()
    }
}

// Per-type ToSql/FromSql impls — the orphan rule forbids a blanket impl, so
// each user enum supplies its own one-liner (auto-generated by M8).
impl ToSql<TaggedUnion<MessageData>, Turso> for MessageData {
    fn to_sql(&self, out: &mut Output<'_, '_, Turso>) -> diesel::serialize::Result {
        encode_for_bind(self, out)
    }
}
impl FromSql<TaggedUnion<MessageData>, Turso> for MessageData {
    fn from_sql(bytes: diesel::turso::TursoValue<'_>) -> diesel::deserialize::Result<Self> {
        decode_from_blob::<Self>(bytes)
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::turso::union::TaggedUnion;
    use super::MessageData;

    messages(id) {
        id -> BigInt,
        data -> TaggedUnion<MessageData>,
    }
}

const SCHEMA: &str = "
    CREATE TYPE telegram_t AS STRUCT(chat_id INT, text TEXT);
    CREATE TYPE slack_t    AS STRUCT(channel_id_hash INT, text TEXT);
    CREATE TYPE message_data AS UNION(telegram telegram_t, slack slack_t);
    CREATE TABLE messages(id INTEGER PRIMARY KEY, data message_data NOT NULL) STRICT;
";

async fn setup() -> Result<TursoConnection> {
    let mut conn = TursoConnection::establish(":memory:").await?;
    conn.batch_execute(SCHEMA).await?;
    Ok(conn)
}

#[tokio::test(flavor = "current_thread")]
async fn insert_and_read_each_variant() -> Result<()> {
    let mut conn = setup().await?;

    diesel::insert_into(messages::table)
        .values((
            messages::id.eq(1i64),
            messages::data.eq(MessageData::Telegram {
                chat_id: -100,
                text: "hi".into(),
            }),
        ))
        .execute(&mut conn)
        .await?;
    diesel::insert_into(messages::table)
        .values((
            messages::id.eq(2i64),
            messages::data.eq(MessageData::Slack {
                channel_id_hash: 777,
                text: Some("yo".into()),
            }),
        ))
        .execute(&mut conn)
        .await?;
    diesel::insert_into(messages::table)
        .values((
            messages::id.eq(3i64),
            messages::data.eq(MessageData::Slack {
                channel_id_hash: 888,
                text: None,
            }),
        ))
        .execute(&mut conn)
        .await?;

    let rows: Vec<(i64, MessageData)> = messages::table
        .order(messages::id.asc())
        .load(&mut conn)
        .await?;
    assert_eq!(
        rows,
        vec![
            (
                1,
                MessageData::Telegram {
                    chat_id: -100,
                    text: "hi".into()
                }
            ),
            (
                2,
                MessageData::Slack {
                    channel_id_hash: 777,
                    text: Some("yo".into())
                }
            ),
            (
                3,
                MessageData::Slack {
                    channel_id_hash: 888,
                    text: None
                }
            ),
        ]
    );
    Ok(())
}

#[tokio::test(flavor = "current_thread")]
async fn server_side_union_tag_still_works() -> Result<()> {
    // Proves turso accepts blobs we encode — it can still compute
    // union_tag() on them, confirming the wire format matches.
    let mut conn = setup().await?;
    diesel::insert_into(messages::table)
        .values((
            messages::id.eq(1i64),
            messages::data.eq(MessageData::Telegram {
                chat_id: 1,
                text: "a".into(),
            }),
        ))
        .execute(&mut conn)
        .await?;
    diesel::insert_into(messages::table)
        .values((
            messages::id.eq(2i64),
            messages::data.eq(MessageData::Slack {
                channel_id_hash: 2,
                text: None,
            }),
        ))
        .execute(&mut conn)
        .await?;

    let mut rows = conn
        .raw()
        .query(
            "SELECT id, CAST(union_tag(data) AS TEXT) FROM messages ORDER BY id",
            (),
        )
        .await?;
    let mut tags = vec![];
    while let Some(r) = rows.next().await? {
        let id = match r.get_value(0)? {
            turso::Value::Integer(i) => i,
            _ => panic!("id"),
        };
        let tag = match r.get_value(1)? {
            turso::Value::Text(s) => s,
            _ => panic!("tag"),
        };
        tags.push((id, tag));
    }
    assert_eq!(tags, vec![(1, "telegram".into()), (2, "slack".into())]);
    Ok(())
}

#[tokio::test(flavor = "current_thread")]
async fn create_type_sql_is_applicable() -> Result<()> {
    // The helper emits the exact DDL that matches this test's SCHEMA; use
    // it to materialise an equivalent schema and prove it applies cleanly.
    let mut conn = TursoConnection::establish(":memory:").await?;
    conn.batch_execute(&MessageData::create_type_sql()).await?;
    conn.batch_execute(
        "CREATE TABLE messages(id INTEGER PRIMARY KEY, data message_data NOT NULL) STRICT",
    )
    .await?;
    diesel::insert_into(messages::table)
        .values((
            messages::id.eq(42i64),
            messages::data.eq(MessageData::Telegram {
                chat_id: 5,
                text: "ok".into(),
            }),
        ))
        .execute(&mut conn)
        .await?;
    let got: MessageData = messages::table
        .find(42i64)
        .select(messages::data)
        .first(&mut conn)
        .await?;
    assert_eq!(
        got,
        MessageData::Telegram {
            chat_id: 5,
            text: "ok".into()
        }
    );
    Ok(())
}
