//! What the typed DSL renders still reaches the indexes it was written for,
//! read through `EXPLAIN QUERY PLAN`.
//!
//! Every other test in this directory asks whether a query returns the right
//! rows. None of them can see the failure this file exists for. A page of one
//! conversation was written as `thread_id IN (SELECT id FROM threads WHERE …)`
//! instead of `thread_id = (SELECT id FROM threads WHERE …)`. The answers were
//! identical — same rows, same order, same count — and one page of a
//! 9.4k-message thread went from 130 microseconds to 12 milliseconds, because
//! the planner stopped walking the compound `(thread_id, date)` index in
//! order, fell back to the primary key's autoindex, and materialised the whole
//! thread into a sorter to satisfy the `ORDER BY`. Nearly a hundredfold, and
//! no functional test anywhere could have noticed.
//!
//! So these tests assert on the *plan*, not on the result. Two properties,
//! and the second is the load-bearing one:
//!
//! - the plan names the index the query was written to use. This catches a
//!   restriction that stopped being sargable at all — a rendering change that
//!   buries a column inside a function, a filter that moved into a subquery,
//!   an index whose leading column no longer matches what the DSL emits.
//! - the plan contains no `USE SORTER FOR ORDER BY`. This is the half that
//!   would actually have caught the 12 ms regression, because that plan still
//!   used *an* index — the PK autoindex — so an assertion on the word "INDEX",
//!   or even on a specific index name, can pass on a plan that is a hundred
//!   times slower. A paged read that sorts is a paged read that touched every
//!   row matching the restriction before returning fifty of them. That is the
//!   whole cost, whatever index served the scan underneath it.
//!
//! Both halves of the contract are written down in places that do not know
//! about each other: the indexes are DDL text in a migration, the queries are
//! typed DSL in Rust, and the SQL that has to make them meet is generated by
//! this backend's `QueryFragment` impls. Any of the three can move without the
//! other two, and when they stop lining up the answers stay correct. That is
//! the class of regression this file is here to make loud.
//!
//! Every query under test is built with the typed DSL. The only raw SQL is the
//! DDL in `batch_execute` and the `EXPLAIN QUERY PLAN` wrapper — which diesel
//! has no expression node for, and whose argument is not hand-written SQL but
//! whatever the DSL rendered a line earlier.

use anyhow::Result;
use diesel::async_dsl::RunQueryDsl;
use diesel::connection::{AsyncConnection, SimpleAsyncConnection};
use diesel::prelude::*;
use diesel::turso::union::{
    CompositeExpressionMethods, TaggedUnion, UnionExpressionMethods, UnionSchema,
};
use diesel::turso::Turso;
use diesel::turso::TursoConnection;
use diesel::UnionSchema as DeriveUnionSchema;

// ── the schema under test ────────────────────────────────────────────────

diesel::table! {
    threads (id) {
        id -> BigInt,
        key -> Text,
        title -> Text,
    }
}

diesel::table! {
    messages (id) {
        id -> BigInt,
        thread_id -> BigInt,
        date -> BigInt,
        body -> Text,
    }
}

diesel::joinable!(messages -> threads (thread_id));
diesel::allow_tables_to_appear_in_same_query!(threads, messages);

/// Two indexes, and every shape below is written for one of them.
///
/// `messages_by_thread_date` is compound and in that order on purpose: it is
/// the index a paged read of one conversation needs, and the only thing that
/// can serve `WHERE thread_id = ? ORDER BY date DESC LIMIT 50` without
/// sorting — the equality pins the leading column, and within that prefix the
/// index is already in `date` order, so the planner can walk it backwards and
/// stop after the page. `threads_by_key` is the unique lookup the scalar
/// subquery in the regression resolved through.
///
/// No `ANALYZE`, and only a handful of rows: what is being tested is the
/// planner's structural reasoning about the schema, which is what a freshly
/// created database — and every database that has never been analysed — runs
/// on. Row counts would only matter if these assertions were about a cost
/// comparison between two viable plans, and none of them are.
async fn setup() -> Result<TursoConnection> {
    let mut conn = TursoConnection::establish(":memory:").await?;
    conn.batch_execute(
        "CREATE TABLE threads(
             id INTEGER PRIMARY KEY,
             key TEXT NOT NULL,
             title TEXT NOT NULL
         ) STRICT;
         CREATE UNIQUE INDEX threads_by_key ON threads(key);

         CREATE TABLE messages(
             id INTEGER PRIMARY KEY,
             thread_id INTEGER NOT NULL,
             date INTEGER NOT NULL,
             body TEXT NOT NULL
         ) STRICT;
         CREATE INDEX messages_by_thread_date ON messages(thread_id, date);

         INSERT INTO threads VALUES (1,'k1','one'),(2,'k2','two');
         INSERT INTO messages VALUES
             (1,1,100,'a'),(2,1,200,'b'),(3,1,300,'c'),(4,2,150,'d');",
    )
    .await?;
    Ok(conn)
}

// ── the helpers ──────────────────────────────────────────────────────────

/// The phrase the whole file is organised around. Turso spells it exactly as
/// SQLite does, and its presence in a paged read is the regression.
const SORTER: &str = "USE SORTER FOR ORDER BY";

#[derive(QueryableByName, Debug)]
struct PlanStep {
    #[diesel(sql_type = diesel::sql_types::Text)]
    detail: String,
}

/// The SQL a query renders to, without the bind values `debug_query` appends
/// after it.
///
/// The binds are dropped rather than substituted because `EXPLAIN QUERY PLAN`
/// compiles a statement instead of running it: the `?` placeholders never need
/// values, so a query can be planned straight from its rendering with nothing
/// bound and nothing executed. That is also why these tests say nothing about
/// the data — the plan is a property of the statement and the schema.
fn rendered<Q>(query: &Q) -> String
where
    Q: diesel::query_builder::QueryFragment<Turso> + diesel::query_builder::QueryId,
{
    let debug = diesel::debug_query::<Turso, _>(query).to_string();
    match debug.split_once(" -- binds:") {
        Some((sql, _)) => sql.to_string(),
        None => debug,
    }
}

/// The planner's answer for `query`: every step, joined with " / ".
///
/// Flattening the step tree into one string is deliberate. Each assertion here
/// asks whether a phrase appears anywhere in the plan, and the nesting adds
/// nothing a `contains` can use. What it gives up is the ability to say *which*
/// loop sorted, and that has never been the question — a sorter anywhere in a
/// paged read means rows were buffered before the `LIMIT` could throw them
/// away.
async fn plan<Q>(conn: &mut TursoConnection, query: &Q) -> Result<String>
where
    Q: diesel::query_builder::QueryFragment<Turso> + diesel::query_builder::QueryId,
{
    let sql = rendered(query);
    // `EXPLAIN QUERY PLAN` is not an expression diesel can build, so this is
    // the one raw statement in the file outside the DDL — and the text inside
    // it is not hand-written SQL, it is what the DSL rendered on the line
    // above.
    let steps: Vec<PlanStep> = diesel::sql_query(format!("EXPLAIN QUERY PLAN {sql}"))
        .load(conn)
        .await?;
    Ok(steps
        .iter()
        .map(|s| s.detail.as_str())
        .collect::<Vec<_>>()
        .join(" / "))
}

/// Assert the planner reaches `index`, and on failure say both what was asked
/// and what it did instead.
///
/// The rendered SQL belongs in the panic message because the interesting
/// failure is almost never "the index disappeared" — it is "the query stopped
/// looking like the thing the index covers", and that is only readable from
/// the SQL the DSL produced.
async fn assert_uses_index<Q>(conn: &mut TursoConnection, query: &Q, index: &str) -> Result<()>
where
    Q: diesel::query_builder::QueryFragment<Turso> + diesel::query_builder::QueryId,
{
    let detail = plan(conn, query).await?;
    assert!(
        detail.contains(index),
        "expected {index} to serve\n  {}\nbut the plan was\n  {detail}",
        rendered(query)
    );
    Ok(())
}

/// Assert the `ORDER BY` is answered by walking an index, not by materialising
/// rows into a sorter.
///
/// This is the assertion the 12 ms plan would have failed and every
/// index-name assertion would have passed. `USE SORTER FOR ORDER BY` means
/// every row matching the restriction was read and buffered before the `LIMIT`
/// could discard all but the first page: on a 9.4k-message thread, 9.4k rows
/// of work to return 50. It is the difference between a paged read whose cost
/// is the page and one whose cost is the conversation.
async fn assert_no_sorter<Q>(conn: &mut TursoConnection, query: &Q) -> Result<()>
where
    Q: diesel::query_builder::QueryFragment<Turso> + diesel::query_builder::QueryId,
{
    let detail = plan(conn, query).await?;
    assert!(
        !detail.contains(SORTER),
        "the ORDER BY should come from an index, not a sorter\n  {}\nplan:\n  {detail}",
        rendered(query)
    );
    Ok(())
}

// ── 1. the paged read ────────────────────────────────────────────────────

/// One page of one conversation — the query the regression was found in, in
/// its correct form, and the baseline every other test here is measured
/// against.
///
/// Turso plans it as `SEARCH messages USING INDEX messages_by_thread_date
/// (thread_id=?)` with no sorter: the equality pins the leading column and
/// the `DESC` ordering is served by walking the index backwards. Both halves
/// are asserted, because an index that served the restriction but not the
/// ordering would still read the whole thread — that is exactly what the slow
/// plan did.
#[tokio::test(flavor = "current_thread")]
async fn paged_read_uses_the_compound_index_and_does_not_sort() -> Result<()> {
    let mut conn = setup().await?;

    let query = messages::table
        .filter(messages::thread_id.eq(1i64))
        .order(messages::date.desc())
        .limit(50);

    assert_uses_index(&mut conn, &query, "messages_by_thread_date").await?;
    assert_no_sorter(&mut conn, &query).await?;
    Ok(())
}

// ── 2. the scalar subquery, compared with `=` ────────────────────────────

/// The shape the regression was about, written the way that keeps the index.
///
/// `.single_value()` wraps the subquery in `(… LIMIT 1)` and `=` compares
/// against it as a scalar. To the planner that is an equality against a value
/// computable once, before the outer loop starts, so the leading column of
/// `messages_by_thread_date` is constrained exactly as it would be by a
/// literal — and, critically, the index ordering survives, so the `ORDER BY`
/// still costs nothing. The subquery does not have to be cheap or
/// uncorrelated; it only has to be *one value*.
///
/// `.assume_not_null()` is the caller asserting the row exists. It changes
/// the Rust type and nothing in the SQL, so it cannot move the plan — it is
/// here because this is the real calling shape, and a test of a shape nobody
/// writes protects nothing.
#[tokio::test(flavor = "current_thread")]
async fn scalar_subquery_compared_with_eq_keeps_the_index() -> Result<()> {
    let mut conn = setup().await?;

    let query = messages::table
        .filter(
            messages::thread_id.eq(threads::table
                .filter(threads::key.eq("k1"))
                .select(threads::id)
                .single_value()
                .assume_not_null()),
        )
        .order(messages::date.desc())
        .limit(50);

    assert_uses_index(&mut conn, &query, "messages_by_thread_date").await?;
    assert_no_sorter(&mut conn, &query).await?;
    Ok(())
}

// ── 3. the `IN (SELECT …)` contrast ──────────────────────────────────────

/// The same restriction written as `IN (SELECT …)`: the shape that cost 12 ms
/// where the `=` above costs 130 microseconds, kept here as the contrast that
/// justifies `assert_no_sorter` existing at all.
///
/// What Turso actually does with it on this schema, verified rather than
/// assumed:
///
/// ```text
/// LIST SUBQUERY 1
///  / SEARCH threads USING COVERING INDEX threads_by_key (key=?)
///  / SEARCH messages USING INDEX messages_by_thread_date (thread_id=?)
///  / USE SORTER FOR ORDER BY
/// ```
///
/// So it is *not* the whole of what the app hit: there the fallback went all
/// the way down to the primary key's autoindex, which on 9.4k rows is what
/// turned the difference into a hundredfold. Here the index is still reached
/// for the restriction. But the expensive half is present and identical — the
/// `IN` turns the subquery into a materialised list, the equality on the
/// leading column becomes a lookup per candidate rather than one range, and
/// the index ordering that made the `ORDER BY` free is gone, so every matching
/// row goes through a sorter before the `LIMIT` can drop it.
///
/// That is precisely why an index-name assertion is not enough. This plan
/// names `messages_by_thread_date`; `assert_uses_index` passes on it. Only the
/// sorter tells the two apart. Hence the paged read above asserts both, and
/// hence this test asserts the sorter is *present*: if a future Turso learns
/// to keep the index ordering through a `LIST SUBQUERY`, this test fails, and
/// that failure is a prompt to re-read this comment rather than a bug.
#[tokio::test(flavor = "current_thread")]
async fn in_subquery_loses_the_index_ordering() -> Result<()> {
    let mut conn = setup().await?;

    let query = messages::table
        .filter(
            messages::thread_id.eq_any(
                threads::table
                    .filter(threads::key.eq("k1"))
                    .select(threads::id),
            ),
        )
        .order(messages::date.desc())
        .limit(50);

    let detail = plan(&mut conn, &query).await?;
    assert!(
        detail.contains("LIST SUBQUERY"),
        "`IN (SELECT …)` should materialise a list: {detail}"
    );
    assert!(
        detail.contains("messages_by_thread_date"),
        "the restriction still reaches the index — which is the trap: {detail}"
    );
    assert!(
        detail.contains(SORTER),
        "the ordering does not survive the list, and this test is the record \
         of that; if Turso has learned better, update the comment above: {detail}"
    );
    Ok(())
}

// ── 4. joins ─────────────────────────────────────────────────────────────

/// An inner join must not cost either side its index — and this backend's join
/// rendering is not diesel's default, so that is a real question here.
///
/// Turso rejects a parenthesized join group in `FROM`, so `Turso` selects
/// diesel's unparenthesized `JoinFromClauseSyntax` (see `joins.rs`). That
/// rendering difference is invisible to a test that only checks rows, and it
/// is the kind of thing that could leave the planner unable to see a
/// restriction through the join.
///
/// It doesn't: both sides are searched through their own index. What the plan
/// *also* contains is a sorter, and the reason is worth writing down, because
/// it is not the join's fault:
///
/// ```text
/// SEARCH threads USING INDEX threads_by_key (key=?)
///  / SEARCH messages USING COVERING INDEX messages_by_thread_date (thread_id=?)
///  / USE SORTER FOR ORDER BY
/// ```
///
/// The restriction is on `threads`, so `threads` drives the loop and
/// `messages` is the inner side; rows arrive grouped by thread rather than in
/// `date` order, so the ordering has to be rebuilt. The second query below is
/// the same join restricted on `messages` instead — `messages` drives, the
/// index walk is already the output order, and the sorter is gone. Same join,
/// same rendering: the sorter follows the loop order, not the join.
#[tokio::test(flavor = "current_thread")]
async fn inner_join_keeps_the_index_on_both_sides() -> Result<()> {
    let mut conn = setup().await?;

    let by_thread_key = messages::table
        .inner_join(threads::table)
        .filter(threads::key.eq("k1"))
        .select((messages::id, threads::title))
        .order(messages::date.desc())
        .limit(50);

    assert_uses_index(&mut conn, &by_thread_key, "threads_by_key").await?;
    assert_uses_index(&mut conn, &by_thread_key, "messages_by_thread_date").await?;

    let detail = plan(&mut conn, &by_thread_key).await?;
    assert!(
        detail.contains(SORTER),
        "restricting on the far table makes it the driver, so the ordering on \
         the near table has to be rebuilt; if this stops being true the \
         comment above needs rewriting: {detail}"
    );

    // The same join, restricted on the ordered table instead.
    let by_message_thread_id = messages::table
        .inner_join(threads::table)
        .filter(messages::thread_id.eq(1i64))
        .select((messages::id, threads::title))
        .order(messages::date.desc())
        .limit(50);

    assert_uses_index(&mut conn, &by_message_thread_id, "messages_by_thread_date").await?;
    assert_no_sorter(&mut conn, &by_message_thread_id).await?;
    Ok(())
}

/// The left join, which is what every "rows with no match on the other side"
/// query is built out of, and the shape where a lost index hurts most: the
/// outer side is walked in full by definition, so the inner side had better be
/// a lookup rather than a scan.
///
/// It is — `SEARCH threads USING INDEX threads_by_key (key=?) / SEARCH
/// messages USING INDEX messages_by_thread_date (thread_id=?) LEFT-JOIN`. The
/// nullability of the right half does not stop the planner from using the
/// index on it, which is the thing worth pinning: a left join that degraded to
/// a scan of `messages` per `threads` row is quadratic and still correct.
#[tokio::test(flavor = "current_thread")]
async fn left_join_keeps_the_index_on_both_sides() -> Result<()> {
    let mut conn = setup().await?;

    let query = threads::table
        .left_join(messages::table.on(messages::thread_id.eq(threads::id)))
        .filter(threads::key.eq("k1"))
        .select((threads::title, messages::body.nullable()));

    assert_uses_index(&mut conn, &query, "threads_by_key").await?;
    assert_uses_index(&mut conn, &query, "messages_by_thread_date").await?;
    Ok(())
}

// ── 5. the expression index over a UNION column ──────────────────────────

#[derive(
    Debug,
    PartialEq,
    Clone,
    diesel::deserialize::FromSqlRow,
    diesel::expression::AsExpression,
    diesel::query_builder::QueryId,
    DeriveUnionSchema,
)]
#[diesel(sql_type = TaggedUnion<EventKey>)]
#[union(name = "event_key")]
pub enum EventKey {
    #[union(struct_type = "telegram_key")]
    Telegram { chat_id: i64, message_id: i64 },
    #[union(struct_type = "email_key")]
    Email { user_id: String, thread_id: String },
}

diesel::table! {
    use diesel::sql_types::*;
    use diesel::turso::union::TaggedUnion;
    use super::EventKey;

    events (mid) {
        mid -> TaggedUnion<EventKey>,
        note -> Text,
    }
}

/// The index is written the way a migration writes one: unqualified column, no
/// parentheses around anything, both projections spelled out in declaration
/// order. What the DSL renders later is not the same string, and that mismatch
/// is the whole point of the test below.
async fn setup_events() -> Result<TursoConnection> {
    let mut conn = TursoConnection::establish(":memory:").await?;
    conn.batch_execute(&EventKey::create_type_sql()).await?;
    conn.batch_execute(
        "CREATE TABLE events(mid event_key PRIMARY KEY, note TEXT NOT NULL) STRICT;
         CREATE INDEX events_tg ON events(
             struct_extract(union_extract(mid, 'telegram'), 'chat_id'),
             struct_extract(union_extract(mid, 'telegram'), 'message_id')
         );",
    )
    .await?;
    Ok(conn)
}

/// An expression index over a UNION column still serves the DSL, even though
/// the two texts do not match.
///
/// This is the sharpest version of the problem this file exists for, because
/// no one author controls both sides. The index says
/// `struct_extract(union_extract(mid, 'telegram'), 'chat_id')` with a bare
/// column name. The DSL renders `struct_extract(union_extract("events"."mid",
/// 'telegram'), 'chat_id')` and parenthesises the comparison around it. Turso's
/// own plan output prints it a third way again, with a space before each
/// argument list: `struct_extract (union_extract (mid, 'telegram'),
/// 'chat_id')`. If expression indexes were matched by text, all three would be
/// different expressions, every one of these queries would silently become a
/// full scan of the table, and every answer would still be right.
///
/// They are matched by comparing resolved expression trees, so qualification,
/// parentheses and whitespace make no difference. The first assertion pins the
/// rendering — a change to what `Extract`/`GetField` emit shows up here as well
/// as in `union_expressions.rs` — and the plan assertions pin that the planner
/// still reaches through it.
///
/// Both the leading column alone and leading-plus-second are covered: an index
/// that matched only on its first column would look identical on the first
/// query and would quietly stop narrowing on the second, which is the shape a
/// range scan within one conversation uses.
#[tokio::test(flavor = "current_thread")]
async fn expression_index_over_a_union_column_serves_the_dsl() -> Result<()> {
    use event_key::telegram;
    let mut conn = setup_events().await?;

    let leading = events::table.filter(
        events::mid
            .extract(telegram::variant)
            .field(telegram::chat_id)
            .eq(-100i64),
    );
    assert!(
        rendered(&leading)
            .contains(r#"struct_extract(union_extract("events"."mid", 'telegram'), 'chat_id')"#),
        "the DSL qualifies the column and the DDL does not — that is the \
         mismatch the planner has to see through: {}",
        rendered(&leading)
    );
    assert_uses_index(&mut conn, &leading, "events_tg").await?;

    let leading_and_second = events::table
        .filter(
            events::mid
                .extract(telegram::variant)
                .field(telegram::chat_id)
                .eq(-100i64),
        )
        .filter(
            events::mid
                .extract(telegram::variant)
                .field(telegram::message_id)
                .ge(7i64),
        );
    assert_uses_index(&mut conn, &leading_and_second, "events_tg").await?;

    // Naming the index is not enough for the two-column case: the plan has to
    // show the second projection inside the index constraint, or the range is
    // being applied row by row after the search rather than narrowing it.
    let detail = plan(&mut conn, &leading_and_second).await?;
    assert!(
        detail.contains("'message_id'"),
        "the second index column should narrow the search, not filter after \
         it: {detail}"
    );
    Ok(())
}

// ── 6. upsert ────────────────────────────────────────────────────────────

/// The conflict target of an upsert reaches its index — checked through the
/// engine's arbiter resolution, because `EXPLAIN QUERY PLAN` has nothing to
/// say about DML on Turso.
///
/// The intended shape of this test was the same as every other one here: plan
/// the `INSERT … ON CONFLICT (key) DO UPDATE` and look for `threads_by_key`.
/// Turso returns *zero* plan rows for an `INSERT`, so the joined plan is the
/// empty string and there is nothing to match on. That emptiness is asserted
/// below rather than worked around, so that if a future Turso starts emitting
/// steps for DML this test fails and can be upgraded to the real thing.
/// (`EXPLAIN` proper does return bytecode, but its result columns do not
/// decode through `QueryableByName` here, and inferring an index from opcodes
/// would be a worse test than the one below.)
///
/// What replaces it is arguably better, because it is the engine's own rule
/// rather than an inference from a plan: a conflict target is resolved to an
/// arbiter index while parsing, and a column with no unique index cannot be
/// one. So the positive case proves the target resolved — the statement
/// compiles, and the conflicting row is updated in place instead of a second
/// row appearing — and the negative case proves the resolution is real and not
/// a formality: the same DSL against `messages.thread_id`, which has an index
/// but a non-unique one, is rejected outright. An upsert whose target drifted
/// off its unique index does not silently degrade to a scan the way a `SELECT`
/// does; it stops working, loudly. Pinning that is what keeps someone from
/// "fixing" it by widening the index.
#[tokio::test(flavor = "current_thread")]
async fn upsert_conflict_target_resolves_to_its_unique_index() -> Result<()> {
    let mut conn = setup().await?;

    let upsert = diesel::insert_into(threads::table)
        .values((
            threads::id.eq(9i64),
            threads::key.eq("k1"),
            threads::title.eq("nine"),
        ))
        .on_conflict(threads::key)
        .do_update()
        .set(threads::title.eq("updated"));

    assert!(
        rendered(&upsert).contains(r#"ON CONFLICT ("key") DO UPDATE SET "title" = ?"#),
        "the conflict target must name the indexed column: {}",
        rendered(&upsert)
    );
    assert_eq!(
        plan(&mut conn, &upsert).await?,
        "",
        "Turso emits no query-plan rows for DML; if it has started to, this \
         test can assert on the plan the way the others do"
    );

    // `k1` already exists, so this takes the conflict path: the arbiter index
    // found the row and `DO UPDATE` rewrote it.
    assert_eq!(upsert.execute(&mut conn).await?, 1);
    let titles: Vec<String> = threads::table
        .select(threads::title)
        .order(threads::id.asc())
        .load(&mut conn)
        .await?;
    assert_eq!(
        titles,
        vec!["updated".to_string(), "two".to_string()],
        "the conflicting row was updated in place, not duplicated"
    );

    // The negative half: `messages_by_thread_date` covers `thread_id`, but it
    // is not unique, so it cannot be an arbiter — and Turso refuses the
    // statement rather than falling back to something slower.
    let err = diesel::insert_into(messages::table)
        .values((
            messages::id.eq(99i64),
            messages::thread_id.eq(1i64),
            messages::date.eq(1i64),
            messages::body.eq("x"),
        ))
        .on_conflict(messages::thread_id)
        .do_update()
        .set(messages::body.eq("y"))
        .execute(&mut conn)
        .await
        .expect_err("a non-unique conflict target has no arbiter index");
    assert!(
        format!("{err:?}").contains("does not match any PRIMARY KEY or UNIQUE constraint"),
        "unexpected error for a non-unique conflict target: {err:?}"
    );
    Ok(())
}

// ── 7. OFFSET without LIMIT ──────────────────────────────────────────────

/// `OFFSET` with no `LIMIT` is free.
///
/// SQLite and Turso both reject a bare `OFFSET`, so this backend injects
/// `LIMIT -1` to make it legal (see `limit_offset.rs`). That injection is
/// invisible to the caller, which is exactly why it is worth checking: a
/// synthesised clause the planner treated as a real bound would change the
/// plan under a query nobody edited. `-1` means "no limit", and it is a
/// literal in the text rather than a bind, so the planner does see it at
/// compile time and could in principle reason about it.
///
/// It doesn't. The plan is identical to the same query with an explicit large
/// limit — index-driven, no sorter, both. Asserting that the two plans are
/// *equal*, rather than that each is separately acceptable, is the point: it
/// says the injection is not observable in the plan at all, which is a stronger
/// and more durable claim than anything about either plan's contents.
#[tokio::test(flavor = "current_thread")]
async fn offset_without_limit_plans_like_an_explicit_limit() -> Result<()> {
    let mut conn = setup().await?;

    let implicit = messages::table
        .filter(messages::thread_id.eq(1i64))
        .order(messages::date.desc())
        .offset(100);
    let explicit = messages::table
        .filter(messages::thread_id.eq(1i64))
        .order(messages::date.desc())
        .limit(1_000_000)
        .offset(100);

    assert!(
        rendered(&implicit).contains("LIMIT -1"),
        "a bare OFFSET should carry the injected sentinel limit: {}",
        rendered(&implicit)
    );

    let with_sentinel = plan(&mut conn, &implicit).await?;
    let with_real_limit = plan(&mut conn, &explicit).await?;
    assert_eq!(
        with_sentinel, with_real_limit,
        "the injected LIMIT -1 must not be visible to the planner"
    );

    assert_uses_index(&mut conn, &implicit, "messages_by_thread_date").await?;
    assert_no_sorter(&mut conn, &implicit).await?;
    Ok(())
}
